[project]
name = "hsir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jayanthh71", email = "jayanth37069@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "yfinance>=1.7.0",
]

[project.scripts]
hsir = "hsir:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
